[build]
  command = "npm run build"
  functions = "./functions" # netlify dev uses this to know where to scaffold and serve your functions
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# note: each of these fields are OPTIONAL
[dev]
  port = 3000 # Port that the dev server will be listening on
  functionsPort = 34567 # port for functions server
  publish = "build" # If you use a _redirect file, provide the path to your static content folder 
